service: selenium-lambda

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  timeout: 900


functions:
  deal_scrape:
    handler: handler.deal_scrape
    layers:
      - ${cf:selenium-layer-dev.SeleniumLayerExport}
      - ${cf:selenium-layer-dev.ChromedriverLayerExport}